<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>    
  <ItemGroup>
    <None Update="TopTradingPartners.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Document.Processor" Version="24.2.5" />
	  <PackageReference Include="DevExpress.Drawing.Skia" Version="24.2.5"/>
	  <PackageReference Include="DevExpress.Win" Version="24.2.5" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
</Project>